<div class="row">
    <div class="small-12 medium-12 large-12 panel">
        <h3>New Customer</h3>
        <section>

            <div class="row">

                <div class="small-12 large-10 columns small-centered">

                    <form action="index/save-queue" method="post">

                        <div class="row">

                            <div class="large-6 small-12 columns">

                                <label>

                                    Service:

                                </label>

                                <select name="service">
                                    <option value=""> --- Select Service ---</option>
                                    <?php foreach ($this->services as $each => $service) { ?>
                                        <option
                                            value="<? echo $service['ServiceId']; ?>"><? echo $service['ServiceTitle']; ?></option>
                                    <?php } ?>
                                </select>

                            </div>

                            <div class="large-6 small-12 columns">

                                <label>

                                    Customer Type:

                                </label>

                                <select name="customerType">
                                    <option value=""> --- Select ---</option>
                                    <option value="citizen">Citizen</option>
                                    <option value="organisation">Organisation</option>
                                    <option value="anonymous">Anonymous</option>

                                </select>

                            </div>
                            <div id="citizenDiv" style="display: none;">
                                <div class="large-4 small-12 columns">

                                    <label>

                                        Title:

                                    </label>

                                    <select name="title">

                                        <option value=""> --- Select ---</option>

                                        <option value="Miss">Miss</option>

                                        <option value="Ms">Ms</option>

                                        <option value="Mrs">Mrs</option>

                                        <option value="Mr">Mr</option>

                                    </select>


                                </div>

                                <div class="large-4 small-12 columns">

                                    <label>

                                        First Name:

                                    </label>

                                    <input type="text" name="firstName"/>


                                </div>

                                <div class="large-4 small-12 columns">

                                    <label>

                                        Last Name:

                                    </label>

                                    <input type="text" name="lastName"/>


                                </div>
                            </div>

                            <div id="organisationDiv" style="display: none;">

                                <div class="large-12 small-12 columns">

                                    <label>

                                        Organisation Name:

                                    </label>

                                    <input type="text" name="organisationName"/>


                                </div>
                            </div>

                            <div class="large-12 small-12 columns">

                                <button>Save</button>

                            </div>

                        </div>

                    </form>

                </div>

            </div>

    </div>

    </section>

    <section>
        <div class="large-12 medium-12 small-12 columns panel">
            <h3>Queue</h3>

            <div class="large-1 medium-2 small-2 columns table-heading">
                #
            </div>
            <div class="large-2 columns hide-for-medium-down table-heading">
                Type
            </div>
            <div class="large-4 medium-6 small-6 columns table-heading">
                Name
            </div>
            <div class="large-3 medium-4 small-4 columns table-heading">
                Service
            </div>
            <div class="large-2 columns hide-for-medium-down table-heading">
                Queued At
            </div>

            <?php foreach ($this->queueItmes as $count => $item) { ?>
                <div class="large-1 medium-2 small-2 columns table">
                    <?php echo $item['QueueItemId']; ?>
                </div>
                <div class="large-2 columns hide-for-medium-down table">
                    <?php echo $item['Type']; ?>
                </div>
                <div class="large-4 medium-6 small-6 columns table">
                    <?php echo $item['Name']; ?>
                </div>
                <div class="large-3 medium-4 small-4 columns table">
                    <?php echo $item['ServiceTitle']; ?>
                </div>
                <div class="large-2 columns hide-for-medium-down table">
                    <?php echo date('d/m/y H:i', strtotime($item['Timestamp'])); ?>
                </div>
            <?php } ?>
        </div>

    </section>

</div>